# Welcome to Jekyll!

#
# This config file is meant for settings that affect your whole blog, values

# which you are expected to set up once and rarely edit after that. If you find

# yourself editing this file very often, consider using Jekyll's data files

# feature for the data you need to update frequently.

#
# For technical reasons, this file is *NOT* reloaded automatically when you use

# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Site settings

# These are used to personalize your new site. If you look in the HTML files,

# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yiwen
SEOTitle: 一文博客 - Yiwen
email: 449202631@qq.com
keywords: 一文博客，前端工程师，yiwenl，yiwenl.cn
description: 一文博客, Yiwen 的个人博客，记录和分享在前端的点滴成长，前端技术，NodeJS。
# this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
# baseurl: "http://www.yiwenl.cn"
# the subpath of your site, e.g. /blog
url: "http://www.yiwenl.cn"
# the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: wenpeng-w

# Build settings
paginate: 10
paginate_path: page/:num
permalink: /:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Static resource path
__CSS__: "/static/css"
__JS__: "/static/js"
__IMG__: "/static/images"

# page navigation
navs:
  - {name: 首页, title: home, url: "/"}
  - {name: 日志归档, title: archives, url: "/archives/"}
  - {name: 分类, title: categories, url: "/categories/"}
  - {name: 关于我, title: about, url: "/about/"}
# Exclude from processing.

# The following items will not be processed, by default. Create a custom list
# to override the default setting.

# exclude:

#   - Gemfile

#   - Gemfile.lock

#   - node_modules

#   - vendor/bundle/

#   - vendor/cache/

#   - vendor/gems/

#   - vendor/ruby/
friends:
  - {name: 剧中人, url: "http://bh-lay.com/"}
  - {name: 蒙奇时光, url: "http://www.muntime.com/"}
  - {name: Falost的小窝, url: "https://www.fedte.cc"}
  - {name: 够过瘾, url: "http://www.gouguoyin.cn/"}
  - {name: 太傅, url: "https://taifua.com/"}
  - {name: 惶心, url: "https://tech.hxco.de/"}